<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FOCUS-QA-118" name="com.focus.testcases.PurchaseVoucherVatTest" tests="140" failures="24" timestamp="22 Feb 2021 19:58:02 GMT" time="2591.766" errors="2">
  <testcase name="checkAvGRateAndAVGRateOBySelectingStdCOGSItemInTenthRowPurchaseVoucherVAT" time="8.249" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxCodeBySelectingFIFOBinItemInSixthRowOfPurchaseVoucherVAT" time="18.454" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkBinPopUpPagePickQtyAfterClickOnOkButtonAndClickOnBinInFourthRowPurchaseVoucherBody" time="6.811" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurhaseVoucherNewEntryPageFooterFields" time="7.104" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxableValueBySelectingWACOGSRMAItemInEigthRowPurchaseVoucherVAT" time="5.274" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkRMAValidationWithDuplicateSerialNumberInPurchaseVoucherVAT" time="13.372" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkRMAValidationWithDuplicateSerialNumberInPurchaseVoucherVAT(PurchaseVoucherVatTest.java:1030)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkRMAValidationWithDuplicateSerialNumberInPurchaseVoucherVAT -->
  <testcase name="checkGrossBySelectingStdCOGSItemInTenthRowPurchaseVoucherVAT" time="12.547" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkSavingOfPurchaseVoucherNewOnClickOkButtonInBillwisePage" time="5.884" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkAvGRateAndAVGRateOBySelectingStandardRateBatchItemInThirdRowPurchaseVoucherBody" time="7.320" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkGrossBySelectingStandardRateItemInFourthRowPurchaseVoucherBody" time="14.035" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkJursidicationValueOnChangeDepartmentAndLocalExchangeRateWithCurrencyINR" time="22.822" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkRowDeleteInPurchaseVoucherVAT" time="7.359" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkExchangeRateAndLocalExchangeRateWithCurrencyINRInPurchaseVoucherVAT" time="10.976" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkCurrencyWithUSD" time="18.509" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherNewSaveInfoPanelDashlet" time="5.533" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkCloseBtnInEntryPageAndCheckLinksDisplayInHomePage" time="13.840" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkDueDateOptioninPurchaseVoucherVATEntryPage" time="6.576" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherNewBillwiseScreenClickOnPick" time="16.814" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkPurchaseVoucherNewBillwiseScreenClickOnPick(PurchaseVoucherVatTest.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPurchaseVoucherNewBillwiseScreenClickOnPick -->
  <testcase name="checkPurchaseVoucherVATEntryPageDocumentNumber" time="10.095" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchasesVoucherPendingLinksOptionsInHomePageOnAuthorization" time="7.418" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkPurchasesVoucherPendingLinksOptionsInHomePageOnAuthorization(PurchaseVoucherVatTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPurchasesVoucherPendingLinksOptionsInHomePageOnAuthorization -->
  <testcase name="checkTaxableValueBySelectingStandardRateItemInThirdRowPurchaseVoucherBody" time="5.160" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkAvGRateAndAVGRateOBySelectingWACOGSRMAItemInEigthRowPurchaseVoucherVAT" time="7.484" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkAvGRateAndAVGRateOBySelectingFIFOBinItemInSixthRowPurchaseVoucherVAT" time="7.020" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkAvGRateAndAVGRateOBySelectingFIFOBinItemInSixthRowPurchaseVoucherVAT(PurchaseVoucherVatTest.java:704)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkAvGRateAndAVGRateOBySelectingFIFOBinItemInSixthRowPurchaseVoucherVAT -->
  <testcase name="checkDepartmentMasterUpdateByClickOnSaveInPurchaseVoucher" time="14.933" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkDepartmentMasterUpdateByClickOnSaveInPurchaseVoucher(PurchaseVoucherVatTest.java:390)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkDepartmentMasterUpdateByClickOnSaveInPurchaseVoucher -->
  <testcase name="checkTaxCodeBySelectingStandardRateItemInPurchaseVoucherBody" time="38.252" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxableValueBySelectingWACOGSRMAItemInSeventhRowPurchaseVoucherVAT" time="7.738" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherNewEntryPageBodyFields" time="7.881" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkVATValueBySelectingStandardRateIteminPurchaseVoucherBody" time="5.247" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkVATValueBySelectingStandardRateItemInFourthRowPurchaseVoucherBody" time="6.708" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkFinancialsMenuTransactionsMenuPurchasesMenu" time="13.449" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherNewHomePage" time="18.293" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkCurrencyOptioninPurchaseVoucherVAT" time="7.769" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkAddAndOkButtonInRmaPageEigthRowOfPurchaseVoucherVAT" time="10.847" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkCreateVendorAccountMasterAuthorization" time="15.294" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkBinPopUpPageInputManualInputInAllocateQtyInPurchaseVoucherVAT" time="33.968" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxableValueBySelectingStdCOGSInTwelevethRowPurchaseVoucherVAT" time="8.950" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherNewInfoPanelDashlet" time="84.053" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkPurchaseVoucherNewInfoPanelDashlet(PurchaseVoucherVatTest.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPurchaseVoucherNewInfoPanelDashlet -->
  <testcase name="checkTaxableValueBySelectingStdCOGSInTenthRowPurchaseVoucherVAT" time="4.941" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkAvGRateAndAVGRateOBySelectingStandardRateBatchItemInSecondRowPurchaseVoucherBody" time="7.430" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherVATWithCurrencyInputAndExcgRate" time="6.306" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherNewEntryPageInfoSideBarCustomizeBtn" time="43.456" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkPurchaseVoucherNewEntryPageInfoSideBarCustomizeBtn(PurchaseVoucherVatTest.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPurchaseVoucherNewEntryPageInfoSideBarCustomizeBtn -->
  <testcase name="checkSavedVoucherInJobOrderAfterSavingVoucherInPVVAT" time="5.962" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkSavedVoucherInJobOrderAfterSavingVoucherInPVVAT(PurchaseVoucherVatTest.java:1069)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavedVoucherInJobOrderAfterSavingVoucherInPVVAT -->
  <testcase name="checkGrossBySelectingFIFOBinItemInFifthRowPurchaseVoucherVAT" time="7.958" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkAvGRateAndAVGRateOBySelectingBinItemInFourthRowPurchaseVoucherBody" time="7.551" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkAvGRateAndAVGRateOBySelectingBinItemInFourthRowPurchaseVoucherBody(PurchaseVoucherVatTest.java:558)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkAvGRateAndAVGRateOBySelectingBinItemInFourthRowPurchaseVoucherBody -->
  <testcase name="checkUpdateItemSettingsAsZeroInFourthRowOfPurchaseVoucherBody" time="30.583" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkSavingVocuherWithAllInputsThroughCopyDocument" time="2.147" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <error type="org.openqa.selenium.ElementClickInterceptedException" message="element click intercepted: Element &lt;td class=&quot;FGridColumn  &quot; onclick=&quot;FGRIDCONTROL.PRIVATE.onCellClick(this, event);&quot; ondblclick=&quot;FGRIDCONTROL.PRIVATE.onCellDblClick(this, event);&quot; onmouseenter=&quot;null&quot; onmouseleave=&quot;null&quot; style=&quot;border: 1px solid rgb(204, 204, 204); overflow-wrap: break-word; white-space: normal; min-width: 120px; max-width: 120px; text-align: left; padding: 0px;&quot; data-value=&quot;...&quot;&gt;sampleBatch&lt;/td&gt; is not clickable at point (834, 308). Other element would receive the click: &lt;tbody id=&quot;RMA_Table_body&quot; class=&quot;custom_scrollbar&quot; style=&quot;display:block;overflow: auto;height: 250px;&quot; onscroll=&quot;FGRIDCONTROL.PRIVATE.onScroll(this, event);&quot;&gt;...&lt;/tbody&gt;
  (Session info: chrome=88.0.4324.182)
Build info: version: &#039;3.12.0&#039;, revision: &#039;7c6e0b3&#039;, time: &#039;2018-05-08T14:04:26.12Z&#039;
System info: host: &#039;FOCUS-QA-118&#039;, ip: &#039;192.168.4.201&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_111&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.182, chrome: {chromedriverVersion: 87.0.4280.20 (c99e81631faa0..., userDataDir: C:\Users\admin\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:56792}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: f26fd230a3d73821a68d0ed2f08b9d58">
      <![CDATA[org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element <td class="FGridColumn  " onclick="FGRIDCONTROL.PRIVATE.onCellClick(this, event);" ondblclick="FGRIDCONTROL.PRIVATE.onCellDblClick(this, event);" onmouseenter="null" onmouseleave="null" style="border: 1px solid rgb(204, 204, 204); overflow-wrap: break-word; white-space: normal; min-width: 120px; max-width: 120px; text-align: left; padding: 0px;" data-value="...">sampleBatch</td> is not clickable at point (834, 308). Other element would receive the click: <tbody id="RMA_Table_body" class="custom_scrollbar" style="display:block;overflow: auto;height: 250px;" onscroll="FGRIDCONTROL.PRIVATE.onScroll(this, event);">...</tbody>
  (Session info: chrome=88.0.4324.182)
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'FOCUS-QA-118', ip: '192.168.4.201', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.182, chrome: {chromedriverVersion: 87.0.4280.20 (c99e81631faa0..., userDataDir: C:\Users\admin\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:56792}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: f26fd230a3d73821a68d0ed2f08b9d58
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:276)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
	at com.sun.proxy.$Proxy15.click(Unknown Source)
	at com.focus.Pages.PurchaseVoucherVatPage.checkSavingVocuherWithAllInputsThroughCopyDocument(PurchaseVoucherVatPage.java:26735)
	at com.focus.testcases.PurchaseVoucherVatTest.checkSavingVocuherWithAllInputsThroughCopyDocument(PurchaseVoucherVatTest.java:1053)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- checkSavingVocuherWithAllInputsThroughCopyDocument -->
  <testcase name="checkAvGRateAndAVGRateBySelectingStdCOGSInEleventhRowPurchaseVoucherVAT" time="7.457" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkAutoAllocateOptionInBinPopupPageInFourthRowPurchaseVoucherBody" time="23.580" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkBinValidationInPurchaseVoucherVAT" time="36.004" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherNewCurrencyHasNotDefinedOptions" time="6.269" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxCodeBySelectingStandardRateItemInSecondRowOfPurchaseVoucherBody" time="17.818" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkSavedVoucherInJobOrder" time="82.803" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkSavedVoucherInJobOrder(PurchaseVoucherVatTest.java:1077)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavedVoucherInJobOrder -->
  <testcase name="checkGrossBySelectingFIFOBinItemInSixthRowPurchaseVoucherVAT" time="9.550" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherNewEntryPageHeaderFields" time="7.744" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxCodeBySelectingStdCOGSInTwelevethRowOfPurchaseVoucherVAT" time="17.241" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxCodeBySelectingStandardRateItemInFourthRowOfPurchaseVoucherBody" time="18.478" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxCodeBySelectingWACOGSRMAItemInNinethRowOfPurchaseVoucherVAT" time="15.531" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkAvGRateAndAVGRateOBySelectingFIFOBinItemInFifthRowPurchaseVoucherVAT" time="9.003" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkAvGRateAndAVGRateOBySelectingFIFOBinItemInFifthRowPurchaseVoucherVAT(PurchaseVoucherVatTest.java:639)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkAvGRateAndAVGRateOBySelectingFIFOBinItemInFifthRowPurchaseVoucherVAT -->
  <testcase name="checkEditVendorAccountToUpdate" time="19.737" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkGrossBySelectingStandardRateIteminPurchaseVoucherBody" time="7.366" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherVATEntryPageFooterFields" time="5.182" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkBatchValidationInPurchaseVoucherVAT" time="195.114" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkBatchValidationInPurchaseVoucherVAT(PurchaseVoucherVatTest.java:982)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkBatchValidationInPurchaseVoucherVAT -->
  <testcase name="checkPurchaseVoucherVATSaveWithOutInput" time="6.459" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxableValueBySelectingStandardRateItemInSecondRowPurchaseVoucherBody" time="8.763" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxCodeBySelectingStdCOGSItemInTenthRowOfPurchaseVoucherVAT" time="17.383" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherVATRowDelete" time="5.472" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkBinPopUpPageSelectBinAllocateQtyThroughDoubleClickInPurchaseVoucherVAT" time="21.011" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxableValueBySelectingWACOGSRMAItemInNinethRowPurchaseVoucherVAT" time="8.439" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkSignInDemoPopupPageOnClickDoNotShowAndCloseToDisplayMenusAndHomePage" time="87.930" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkSignInDemoPopupPageOnClickDoNotShowAndCloseToDisplayMenusAndHomePage(PurchaseVoucherVatTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSignInDemoPopupPageOnClickDoNotShowAndCloseToDisplayMenusAndHomePage -->
  <testcase name="checkPurchaseVoucherNewEntryPageDocumentNumber" time="4.857" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkVATValueBySelectingStdCOGSInTwelevethRowPurchaseVoucherVAT" time="7.072" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkGrossBySelectingStdCOGSInTwelevethRowPurchaseVoucherVAT" time="11.688" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPickOptionInBinPopupPageInFourthRowOfPurchaseVoucherVAT" time="24.503" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherNewBillwise" time="19.493" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkPurchaseVoucherNewBillwise(PurchaseVoucherVatTest.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPurchaseVoucherNewBillwise -->
  <testcase name="checkBatchValueandExpireyDateInPurchaseVoucherBody" time="10.551" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherNewDueDateOption" time="13.071" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkVATValueBySelectingStdCOGSInTenthRowPurchaseVoucherVAT" time="8.620" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkVATValueBySelectingFIFOBinItemInFifthRowPurchaseVoucherVAT" time="4.991" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherVATCopyDocumentOption" time="4.229" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkPurchaseVoucherVATCopyDocumentOption(PurchaseVoucherVatTest.java:1038)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPurchaseVoucherVATCopyDocumentOption -->
  <testcase name="checkPurchaseVoucherNewEntryPageInfoSideBarReportOption" time="84.153" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkPurchaseVoucherNewEntryPageInfoSideBarReportOption(PurchaseVoucherVatTest.java:222)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPurchaseVoucherNewEntryPageInfoSideBarReportOption -->
  <testcase name="checkAvGRateAndAVGRateOBySelectingStdCOGSInTwelevethRowPurchaseVoucherVAT" time="9.311" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkAvGRateAndAVGRateOBySelectingStandardRateBatchItemInPurchaseVoucherBody" time="10.162" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkCancelOptionInBinPopUpPageInFourthRowPurchaseVoucherBody" time="12.450" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherNewEntryPageInfoSideBarOtherDashletsOption" time="6.962" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherNewEntryPageInfoSideBarGraphOption" time="82.825" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkPurchaseVoucherNewEntryPageInfoSideBarGraphOption(PurchaseVoucherVatTest.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPurchaseVoucherNewEntryPageInfoSideBarGraphOption -->
  <testcase name="checkGrossBySelectingStdCOGSItemInEleventhRowPurchaseVoucherVAT" time="13.215" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkAvGRateAndAVGRateOBySelectingWACOGSRMAItemInSeventhRowPurchaseVoucherVAT" time="8.990" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherVATVendorOptions" time="5.247" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkAvGRateAndAVGRateOBySelectingWACOGSRMAItemInNinethRowPurchaseVoucherVAT" time="8.178" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchasesVoucherOpenEntryByConvertOpyionInHomePageOnLinksView" time="44.909" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkPurchasesVoucherOpenEntryByConvertOpyionInHomePageOnLinksView(PurchaseVoucherVatTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPurchasesVoucherOpenEntryByConvertOpyionInHomePageOnLinksView -->
  <testcase name="checkStandardRateOptionByVoucherEdit" time="20.931" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkStandardRateOptionByVoucherEdit(PurchaseVoucherVatTest.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkStandardRateOptionByVoucherEdit -->
  <testcase name="checkPurchaseVoucherNewEntryPageInfoSideBarInfoPanelOption" time="82.801" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkPurchaseVoucherNewEntryPageInfoSideBarInfoPanelOption(PurchaseVoucherVatTest.java:229)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPurchaseVoucherNewEntryPageInfoSideBarInfoPanelOption -->
  <testcase name="checkVATValueBySelectingStdCOGSItemInEleventhRowPurchaseVoucherVAT" time="5.224" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkVATValueBySelectingWACOGSRMAItemInNinethRowPurchaseVoucherVAT" time="5.324" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkSavingOfPurchaseVoucherVATOnClickOkButtonInBillwisePage" time="8.465" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkVendorAccountBlankNarrationToDisplayCaptionItem" time="3.203" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkGrossBySelectingWACOGSRMAItemIEigthRowPurchaseVoucherVAT" time="12.089" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxableValueBySelectingStdCOGSItemInEleventhRowPurchaseVoucherVAT" time="6.434" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkVATValueBySelectingWACOGSRMAItemInEightRowPurchaseVoucherVAT" time="7.051" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherNewEntryPageInfoSideBarSearch" time="7.030" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkGrossBySelectingStandardRateItemInThirdRowPurchaseVoucherBody" time="10.668" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherVATEntryPageHeaderFields" time="5.610" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherVATDepartment" time="3.578" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxableValueBySelectingStandardRateItemInFourthRowPurchaseVoucherBody" time="5.008" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkVATValueBySelectingWACOGSRMAItemInSeventhRowPurchaseVoucherVAT" time="6.790" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkVATValueBySelectingFIFOBinItemInSixthRowPurchaseVoucherVAT" time="9.080" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxCodeBySelectingStdCOGSInEleventhRowOfPurchaseVoucherVAT" time="16.989" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkAddAndOkButtonInRmaPageOfPurchaseVoucherVAT" time="9.615" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkCopyDocumentOptioninPurchaseVoucherVAT" time="23.133" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkCopyDocumentOptioninPurchaseVoucherVAT(PurchaseVoucherVatTest.java:1046)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkCopyDocumentOptioninPurchaseVoucherVAT -->
  <testcase name="checkCurrencyWithAED" time="5.182" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherNewEntryPageInfoSideBar" time="19.731" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxCodeBySelectingStandardRateItemInThirdRowOfPurchaseVoucherBody" time="17.376" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherVATSaveWithVendorInput" time="5.047" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkSuspedingPurchaseVoucherVatVoucherOnPreviousButton" time="3.191" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <error type="org.openqa.selenium.ElementClickInterceptedException" message="element click intercepted: Element &lt;div id=&quot;id_transactionentry_close&quot; class=&quot;btn toolbar_button theme_button_color default_padding_toolbar_button&quot; onclick=&quot;TRANSACTION_ENTRY.TOOLBAR.onClose_Click(this, event);&quot;&gt;...&lt;/div&gt; is not clickable at point (1281, 77). Other element would receive the click: &lt;div class=&quot;modal modal-wide fade in&quot; role=&quot;dialog&quot; id=&quot;MAinRMAPOpUP&quot; data-backdrop=&quot;static&quot; data-keyboard=&quot;false&quot; data-rmaalwaysnumeric=&quot;False&quot; data-inputrmanobeforequantity=&quot;False&quot; data-rowno=&quot;3&quot; data-scallback=&quot;TRANSACTION_ENTRY.CALLBACK.rmaResult&quot; style=&quot;top: 67.375px; display: block; padding-right: 6px;&quot;&gt;...&lt;/div&gt;
  (Session info: chrome=88.0.4324.182)
Build info: version: &#039;3.12.0&#039;, revision: &#039;7c6e0b3&#039;, time: &#039;2018-05-08T14:04:26.12Z&#039;
System info: host: &#039;FOCUS-QA-118&#039;, ip: &#039;192.168.4.201&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_111&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.182, chrome: {chromedriverVersion: 87.0.4280.20 (c99e81631faa0..., userDataDir: C:\Users\admin\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:56792}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: f26fd230a3d73821a68d0ed2f08b9d58">
      <![CDATA[org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element <div id="id_transactionentry_close" class="btn toolbar_button theme_button_color default_padding_toolbar_button" onclick="TRANSACTION_ENTRY.TOOLBAR.onClose_Click(this, event);">...</div> is not clickable at point (1281, 77). Other element would receive the click: <div class="modal modal-wide fade in" role="dialog" id="MAinRMAPOpUP" data-backdrop="static" data-keyboard="false" data-rmaalwaysnumeric="False" data-inputrmanobeforequantity="False" data-rowno="3" data-scallback="TRANSACTION_ENTRY.CALLBACK.rmaResult" style="top: 67.375px; display: block; padding-right: 6px;">...</div>
  (Session info: chrome=88.0.4324.182)
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'FOCUS-QA-118', ip: '192.168.4.201', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.182, chrome: {chromedriverVersion: 87.0.4280.20 (c99e81631faa0..., userDataDir: C:\Users\admin\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:56792}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: f26fd230a3d73821a68d0ed2f08b9d58
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:276)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
	at com.sun.proxy.$Proxy15.click(Unknown Source)
	at com.focus.Pages.PurchaseVoucherVatPage.checkSuspedingPurchaseVoucherVatVoucherOnPreviousButton(PurchaseVoucherVatPage.java:27131)
	at com.focus.testcases.PurchaseVoucherVatTest.checkSuspedingPurchaseVoucherVatVoucherOnPreviousButton(PurchaseVoucherVatTest.java:1061)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- checkSuspedingPurchaseVoucherVatVoucherOnPreviousButton -->
  <testcase name="checkGrossBySelectingWACOGSRMAItemInNinethRowPurchaseVoucherVAT" time="10.553" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxableValueBySelectingStandardRateItemAndClickonSaveWithoutBatch" time="11.535" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherNewEntryPageInfoSideBarWorkFlowOption" time="82.855" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkPurchaseVoucherNewEntryPageInfoSideBarWorkFlowOption(PurchaseVoucherVatTest.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPurchaseVoucherNewEntryPageInfoSideBarWorkFlowOption -->
  <testcase name="checkTotalConsumedBinValidationInPurchaseVoucherVAT" time="18.508" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkVATValueBySelectingStandardRateItemInThirdRowPurchaseVoucherBody" time="5.401" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkBatchValueInThirdRowPurchaseVoucherBody" time="9.278" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkVATValueBySelectingStandardRateItemInSecondRowPurchaseVoucherBody" time="5.292" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxCodeBySelectingWACOGSRMAItemInEightRowOfPurchaseVoucherVAT" time="19.877" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxableValueBySelectingFIFOBinItemInFifthRowPurchaseVoucherVAT" time="10.606" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkExchangeRateAndLocalExchangeReateWithCurrencyUSD" time="7.289" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkGrossBySelectingWACOGSRMAItemInSeventhRowPurchaseVoucherVAT" time="7.533" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkRMAValidationInPurchaseVoucherVAT" time="118.033" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkRMAValidationInPurchaseVoucherVAT(PurchaseVoucherVatTest.java:1022)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkRMAValidationInPurchaseVoucherVAT -->
  <testcase name="checkBinPopUpPageAfterClickOnCancelAndClickOnBinInFourthRowPurchaseVoucherBody" time="32.340" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkAddAndOkButtonInRmaPageNinethRowOfPurchaseVoucherVAT" time="9.611" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxableValueBySelectingFIFOBinItemInSixthRowPurchaseVoucherVAT" time="6.771" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkChangingWareHouseAfterBinAllocatedinPurchaseVoucherVAT" time="21.895" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherVATBillwiseScreenClickOnPick" time="17.850" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkDepartmentEditExchangeRateAndLocalExchangeReateWithCurrencyAEDInPV" time="24.436" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxCodeBySelectingFIFOBinItemInFifthRowOfPurchaseVoucherVAT" time="16.146" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherVATEntryPageBodyFields" time="7.759" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkGrossBySelectingStandardRateItemInSecondRowPurchaseVoucherBody" time="9.300" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkPurchaseVoucherVATBillwisePage" time="21.273" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkBatchValueInSecondRowPurchaseVoucherBody" time="10.616" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkTaxCodeBySelectingWACOGSRMAItemInSeventhRowOfPurchaseVoucherVAT" time="15.973" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkBinPopUpPageInFourthRowPurchaseVoucherBody" time="28.486" classname="com.focus.testcases.PurchaseVoucherVatTest"/>
  <testcase name="checkINVTagTaxCodeBySelectingStandardRateItemInPurchaseVoucherBody" time="104.817" classname="com.focus.testcases.PurchaseVoucherVatTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVoucherVatTest.checkINVTagTaxCodeBySelectingStandardRateItemInPurchaseVoucherBody(PurchaseVoucherVatTest.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkINVTagTaxCodeBySelectingStandardRateItemInPurchaseVoucherBody -->
</testsuite> <!-- com.focus.testcases.PurchaseVoucherVatTest -->
