<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FOCUS-QA-10" name="com.focus.testcases.MasterBuyingAndSellingTest" tests="18" failures="2" timestamp="13 Oct 2022 17:26:18 GMT" time="135.091" errors="0">
  <testcase name="verifySavedSellerRatesInformation" time="5.604" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
  <testcase name="verifySaveSellerPriceBook" time="8.440" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
  <testcase name="verifyCustomizeColumnsInSellerPricebook" time="9.764" classname="com.focus.testcases.MasterBuyingAndSellingTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.MasterBuyingAndSellingTest.verifyCustomizeColumnsInSellerPricebook(MasterBuyingAndSellingTest.java:342)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyCustomizeColumnsInSellerPricebook -->
  <testcase name="verifyBuyerPriceBook" time="21.866" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
  <testcase name="verifyUpdateSellerPriceBook" time="14.987" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
  <testcase name="verifyMandatoryFieldsInSellerPriceBook" time="3.643" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
  <testcase name="verifySellerPriceBook" time="5.539" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
  <testcase name="verifyProductMandatory" time="3.980" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
  <testcase name="checkSellerPricebookWithInactive" time="10.635" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
  <testcase name="verifySellerPriceBookRate" time="5.991" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
  <testcase name="verifyEditSellerPriceBook" time="6.240" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
  <testcase name="verifyCustomizeColumnsAfterInputofSellerPriceName" time="3.206" classname="com.focus.testcases.MasterBuyingAndSellingTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.MasterBuyingAndSellingTest.verifyCustomizeColumnsAfterInputofSellerPriceName(MasterBuyingAndSellingTest.java:351)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyCustomizeColumnsAfterInputofSellerPriceName -->
  <testcase name="verifyCloseOptionAfterSavingInactiveInSellerPriceBook" time="5.958" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
  <testcase name="verifyCloseInSellerPriceBook" time="3.331" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
  <testcase name="verifySellerPricebookNoOptionOnClickOnDelete" time="2.470" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
  <testcase name="verifyCopyClearPasteDeleteOption" time="17.352" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
  <testcase name="verifySellerPricebookSettingsOption" time="2.612" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
  <testcase name="verifySellerPricebookYesOptionOnClickDelete" time="3.473" classname="com.focus.testcases.MasterBuyingAndSellingTest"/>
</testsuite> <!-- com.focus.testcases.MasterBuyingAndSellingTest -->
